### ISSUE TITLE
RuuviTag shipping new firmware with different data format

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/ruuvitag-adapter#10] opened 2020-06-11 16:45 UTC
I bought a 3 pack of RuuviTags and finally got them recognised (I caused that issue :) ).

In the gateway, the things look like this
![image](https://user-images.githubusercontent.com/65324897/84415526-78586000-ac45-11ea-93cc-f900a69e8784.png)
From what I can understand, tags shipped since October 2019 come with new firmware with a new data format. Ruuvi published a javascript parser at https://github.com/ruuvi/ruuvi.endpoints.js

Please could you have a look and consider integrating?

**Comment by chas-iot** [comment] 2020-06-11 17:24
If it's helpful, I added a line to log the data
```
console.log(id,': ',JSON.stringify(manufacturerData));
```

```
2020-06-12 00:06:20.941 INFO   : ruuvitag-adapter: Detected new RuuviTag with id c68595ba4031
2020-06-12 00:06:20.947 INFO   : ruuvitag-adapter: c68595ba4031 :  {"type":"Buffer","data":[153,4,5,22,174,113,152,198,18,0,68,0,16,3,236,194,182,48,58,204,198,133,149,186,64,49]}
2020-06-12 00:06:22.420 INFO   : ruuvitag-adapter: Detected new RuuviTag with id e8c780e741c9
2020-06-12 00:06:22.421 INFO   : ruuvitag-adapter: e8c780e741c9 :  {"type":"Buffer","data":[153,4,5,22,90,119,9,198,129,254,96,253,44,254,16,197,182,117,145,85,232,199,128,231,65,201]}
2020-06-12 00:06:29.946 INFO   : ruuvitag-adapter: Detected new RuuviTag with id f6c6b6f848b9
2020-06-12 00:06:29.951 INFO   : ruuvitag-adapter: f6c6b6f848b9 :  {"type":"Buffer","data":[153,4,5,22,178,115,90,197,191,0,24,0,0,3,200,199,54,205,85,105,246,198,182,248,72,185]}
```

**Comment by tim-hellhake** [comment] 2020-06-11 22:09
Extending the parser was also on my todo list.
I just added unit tests for the existing parser using the official test data.
I'll add the remaining properties soon.

> Ruuvi published a javascript parser at https://github.com/ruuvi/ruuvi.endpoints.js

I think the parser was intended for this [this](https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/ruuvi-endpoints.md).
I'm not sure if the GATT endpoints use exactly the same structure as the advertisement packets.

**Comment by chas-iot** [comment] 2020-06-12 00:44
Sorry, I was not clear in my original report, the issue is that the temperatures are not correct. I live in Singapore, so temperatures should be in the range of 24C to 36C. With my new RuuviTags, the temperatures are displayed in the range of -49C to +81C which I could not survive at either end :)

I believe the data is published in a new format version 5 in tags shipped since October last year. It may be possible to upgrade the firmware on an existing tag to publish data in this format.

**Comment by chas-iot** [comment] 2020-06-12 03:48
See https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/broadcast_formats.md
particularly the two sections headed
- [Data format 3 (also known as RAWv1)](https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/broadcast_formats.md#data-format-3-also-known-as-rawv1)
- [Data format 5 (also known as RAWv2)](https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/broadcast_formats.md#data-format-5-also-known-as-rawv2)

**Comment by chas-iot** [comment] 2020-06-12 08:19
I have got it working and with most of the additional properties. However I did it by hacking the generated javascript. I'll see can I get it into TypeScript and give you a pull request in the next 24 hours

**Comment by tim-hellhake** [comment] 2020-06-12 13:25
> I was not clear in my original report

My fault, I didn't see the negative temperatures in the screenshot 😬.

> I'll see can I get it into TypeScript and give you a pull request in the next 24 hours

Thank you for that!
I added the issue number to the commit message, so it is linked here.

**Comment by tim-hellhake** [comment] 2020-06-12 13:39
I added assertions for the new properties.
Seems to be fine according to the official test data :)

**Comment by tim-hellhake** [comment] 2020-06-12 13:54
I added the parse methods for the V3 format so we have the new properties in both formats.

**Comment by tim-hellhake** [comment] 2020-06-14 15:25
Can we also close this?

**Comment by chas-iot** [comment] 2020-06-14 15:27
yes, it should be closed

**Closed as completed** 2020-06-14 15:27 UTC
